---
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicy
metadata:
  name: crossplane-cluster
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   ["devopstoolkitseries.com"]
      apiVersions: ["v1alpha1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["clusterclaims", "compositeclusters"]
  validations:
  - expression: "object.spec.parameters.nodeSize.matches('^small|medium|large$')"
    message: "nodeSize must be one of small, medium, or large"
---
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: crossplane-cluster
spec:
  policyName: crossplane-cluster
  matchResources:
    namespaceSelector:
      matchExpressions:
      - key: environment
        operator: NotIn
        values:
        - silly
---
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicy
metadata:
  name: crossplane-cluster-production
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   ["devopstoolkitseries.com"]
      apiVersions: ["v1alpha1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["clusterclaims", "compositeclusters"]
  validations:
  - expression: "object.spec.parameters.nodeSize.matches('^medium|large$')"
    message: "nodeSize must be one of medium or small"
  - expression: "object.spec.parameters.minNodeCount <= 10"
    message: "minNodeCount must be less than or equal to 10"
  - expression: "object.spec.parameters.version.matches('^1[.]2[4-6]$')"
    message: "version must be one of 1.24, 1.25, or 1.26"
---
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: crossplane-cluster-production
spec:
  policyName: crossplane-cluster-production
  matchResources:
    namespaceSelector:
      matchLabels:
        environment: production
